// {
//     cardImgSrc: "./Images/Prakhar1.jpg",
//     cardName: "Your Name",
//     cardCollege: "Name of your college/organization",
//     cardYear: "Your Year",
//     cardBranch: "Your Branch Here",
//     cardTwitter: "Your Twitter Link Here",
//     cardLinkedin: "Your LinkedIn Link Here",
//     cardGithub: "Your Website Link Here",
//     cardWebsite: "https://prakharsharma.software",
// },

export const profiles = [
  {
    cardImgSrc: "./Images/Prakhar1.jpg",
    cardName: "Prakhar Sharma",
    cardCollege: "MaharajaAgrasen Institute of Technology",
    cardYear: "4th Year",
    cardBranch: "Computer Networking",
    cardTwitter: "https://twitter.com/prakhar_2206",
    cardLinkedin: "https://www.linkedin.com/in/prakhar-sharma-2206",
    cardGithub: "https://github.com/Prakharsharma2206",
    cardWebsite: "https://prakharsharma.software",
  },
  {
    cardImgSrc: "./Images/Kushaggra.jpg",
    cardName: "Kushaggra Sharma",
    cardCollege: "Telstra",
    cardYear: "2nd Year",
    cardBranch: "Computer Networking",
    cardTwitter: "#",
    cardLinkedin: "https://www.linkedin.com/in/kushaggra-sharma/",
    cardGithub: "https://github.com/Kushaggra",
    cardWebsite: "#",
  },
  {
    cardImgSrc: "./Images/tiansing.jpg",
    cardName: "Christian Igbaras",
    cardCollege: "SurPathHub",
    cardYear: "4th Year",
    cardBranch: "Information Systems",
    cardTwitter: "#",
    cardLinkedin: "https://www.linkedin.com/in/christian-igbaras-41b8a8203/",
    cardGithub: "https://github.com/Tiansing",
    cardWebsite: "#",
  },
  {
    cardImgSrc: "./Images/yagyesh.jpg",
    cardName: "Yagyesh Bobde",
    cardCollege: "Anchors",
    cardYear: "1st Year",
    cardBranch: "Computer Science",
    cardTwitter: "https://bit.ly/yb-twitter",
    cardLinkedin: "https://bit.ly/yb-linkedin",
    cardGithub: "https://bit.ly/github_yb",
    cardWebsite: "https://bit.ly/yb-linkedin",
  },
  {
    cardImgSrc: "./Images/Vardaan.jpg",
    cardName: "Vardaan Aggarwal",
    cardCollege: "Vivekananda Institute Of Professional Studies",
    cardYear: "2nd Year",
    cardBranch: "BCA",
    cardTwitter: "https://twitter.com/VardaanAgg",
    cardLinkedin: "https://www.linkedin.com/in/vardaanaggarwal/",
    cardGithub: "https://github.com/VardaanAggarwal",
    cardWebsite: "https://bio.link/vardaanagg",
  },
];
